apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-cedar-webapi-backend2-deployment
spec:
  selector:
    matchLabels:
      app: va-cedar-webapi-backend2-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: va-cedar-webapi-backend2-pod
    spec:
      containers:
      - name: va-cedar-webapi-backend2-container
        image: acrvacedar.azurecr.io/va-cedar-webapi-backend2-practice:#{Build.BuildId}#
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: va-cedar-webapi-backend2-service
spec:
  selector:
    app: va-cedar-webapi-backend2-pod
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
