apiVersion: v1
kind: Service
metadata:
  name: va-cedar-webapi-backend2-service
spec:
  selector:
    app: va-cedar-webapi-backend2-pod
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
